---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        ruby: {}
        javascript: {}
  fixme:
    enabled: true
  rubocop:
    enabled: true
    config: config/.rubocop.yml
ratings:
  paths:
  - "**.rb"
  - Gemfile.lock
exclude_paths:
- "config/**/*"
- "db/**/*"
- "spec/**/*"
- "Gemfile"
